# Generated by Django 4.2.5 on 2023-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_alter_group_name_alter_group_teacher"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={},
        ),
        migrations.RemoveField(
            model_name="student",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.AddField(
            model_name="student",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="groups.group"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
    ]
