# Generated by Django 4.2.5 on 2023-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_student_options_remove_student_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.CharField(default="2005", max_length=4),
        ),
    ]
