# Generated by Django 4.2.5 on 2023-10-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=75, verbose_name="Название предмета"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={},
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subject",
        ),
        migrations.AddField(
            model_name="teacher",
            name="birth_date",
            field=models.DateField(default="2000-01-01", verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="ФИО"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.CharField(default="Математика", max_length=100),
        ),
    ]
