# Generated by Django 4.2.5 on 2023-10-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_subject_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Название педмета"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="birth_date",
            field=models.DateField(),
            default="2000-01-01"

        ),
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teachers.subject",
                verbose_name="Предметы",
            ),
        ),
    ]
