# Generated by Django 4.2.5 on 2023-10-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_subject_alter_teacher_options_and_more"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Назва групи"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="teachers.teacher",
                verbose_name="Вчитель",
            ),
        ),
    ]
